// Generated by CoffeeScript 2.3.0
//if node
//elseif rn
//import Expo, { FileSystem, SQLite } from 'expo'
//endif
var O, OUT, UT, trace;

O = require('./O');

trace = require('./trace');

UT = require('./UT');

// THIS REQUIRED A separate FILE FROM UT.coffee because of a perceived cyclical dependency problem

//if ut
OUT = class OUT extends UT {
  constructor() {
    super("OUT");
  }

  run() {
    return this.s("LOG", function(ut) {
      this.t("(LOG)simple", function(ut) {
        var o, p;
        if (trace.UT_TEST_LOG_ENABLED) {
          O.LOG(null);
          O.LOG(3.1415926);
          O.LOG({
            a: "a"
          });
          O.LOG(["a", "b"]);
          O.LOG([[[["a", "b"], "c"], "b"], "c"]);
          o = {};
          o.z = "some value";
          o.a = "some value";
          o.q = "some value";
          o.k = "some value";
          o.r = "some value";
          for (p in o) {
            this.log(`p=${p}`);
          }
          return O.LOG(o);
        }
      });
      return this.t("(LOG)multiple parameters", function(ut) {
        if (trace.UT_TEST_LOG_ENABLED) {
          O.LOG("peter", "charles", "alvin");
          return O.LOG({
            "a": "peter"
          }, {
            "b": "charles"
          }, {
            "c": "alvin"
          });
        }
      });
    });
  }

};

//endif
module.exports = {
  //if ut
  UTRun: function() {
    return new OUT().run();
  }
};

//endif
