// Generated by CoffeeScript 2.3.0
//if node
//elseif rn
//import Expo, { FileSystem, SQLite } from 'expo'
//endif
var ProofUT, UT, V, fff, trace;

trace = require('./trace');

UT = require('./UT');

V = require('./V');

//if ut
ProofUT = class ProofUT extends UT {
  constructor() {
    super();
  }

  run() {
    //H: 16:07 [UT] ================== #3 ProofUT/LOG/ooooo      where does LOG come from???
    return this.t("type investigation", {
      SO: 2051893
    }, function() {
      this.eq(typeof "string", "string");
      this.eq(typeof String("string"), "string");
      return this.eq(typeof new String("string"), "object");
    });
  }

};

//endif
module.exports = {
  //if ut
  s_ut: function() {
    return new ProofUT().run();
  }
};

return;

//endif

//#################################
console.log("A", "B", "C");

fff = function(x) {
  return 2 * x;
};

console.log(fff(5, fff(6))); //WRONG

trace = require('./trace');

//		list = []
//		list.unshift "a"
//		list.unshift "b"
//		@log list.pop()
//		list.unshift "c"
//		@log list.pop()
//		@log list.pop()
//		@log list.pop()

// https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
// https://stackoverflow.com/questions/36878850/octal-literals-are-not-allowed-in-strict-mode
this.log("hello\\033[0;31mthere");

//MOVE: TO PROOF
//array1 = [
//	'a'
//	'b'
//	'c'
//]
//array1.forEach (element) ->
//	console.log element

//MOVE: proof
console.log(ClientFBUT.this_is_static);

console.log(ClientFBUT.static_method());

console.log(ClientFBUT.this_is_static);

//class ClientFBUT extends UT
//	@this_is_static: 3
//	@static_method: ->
//		@this_is_static++
//#		@log "@this_is_static=#{@this_is_static}"
