// Generated by CoffeeScript 2.3.0
var trace;

trace = require('./trace');

//		list = []
//		list.unshift "a"
//		list.unshift "b"
//		@log list.pop()
//		list.unshift "c"
//		@log list.pop()
//		@log list.pop()
//		@log list.pop()
