// Generated by CoffeeScript 2.3.0
//if NODE
var Base, FBClientNode, TestClient, trace, util;

Base = require('./Base');

FBClientNode = require('./FBClientNode');

trace = require('./trace');

util = require('./Util');

//endif

//H: deprecate?  value?
TestClient = class TestClient extends Base {
  constructor(testHub) {
    super("TestClient");
    this.testHub = testHub;
  }

  //TODO: deprecate necessity to call start()... it's just an extra step I'll forget to do
  start() {
    if (trace.TEST_CLIENT) {
      this.log(`START ${this.testHub.URLGet()}`);
    }
    this.client = new FBClientNode(this.testHub.c, "/tmp/ut/TestClient");
    //		@log "[#{attemptCnt}] attempting to connect to WebSocket #{URL}"
    return this.client.start(this.testHub.URLGet());
  }

};

module.exports = TestClient;
