// Generated by CoffeeScript 2.3.0
var DUMP, trace;

trace = require('./trace');

DUMP = function(v) {
  if (Object.prototype.toString.call(v) === '[object String]') {
    if (v.length === 0) {
      return "\"\"";
    } else {
      return v;
    }
  } else if (Object.prototype.toString.call(v) === '[object Number]') {
    return v;
  } else if (Object.prototype.toString.call(v) === '[object Boolean]') {
    return v;
  } else if (Object.prototype.toString.call(v) === '[object Function]') {
    return "FN";
  } else {
    return `${pv} <${typeof pv}>`;
  }
};

module.exports = {
  DUMP: DUMP
};
